apiVersion: apps/v1
kind: Deployment
metadata:
  name: nm-web-server
  namespace: nm
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: nm-web-server
    app.kubernetes.io/part-of: nm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/name: nm-web-server
      app.kubernetes.io/part-of: nm
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/name: nm-web-server
        app.kubernetes.io/part-of: nm
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: nm-web-server
        image: localhost:5005/nm/nm_web_server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.25"
