apiVersion: v1
kind: Service
metadata:
  name: nm-web-server
  namespace: nm
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: nm-web-server
    app.kubernetes.io/part-of: nm
spec:
  type: LoadBalancer
  ports:
  - name: nm-web-server
    port: 80
    protocol: TCP
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: nm-web-server
    app.kubernetes.io/part-of: nm
